/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopSlugRouteImport } from './routes/shop_.$slug'
import { Route as DashboardTrackProductionRouteImport } from './routes/dashboard.track-production'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardReorderRouteImport } from './routes/dashboard.reorder'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard.quotes'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardArtworkRouteImport } from './routes/dashboard.artwork'
import { Route as DashboardAddressesRouteImport } from './routes/dashboard.addresses'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProductionRouteImport } from './routes/admin.production'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDeliveriesRouteImport } from './routes/admin.deliveries'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminArtworkRouteImport } from './routes/admin.artwork'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as DashboardArtworkUploadRouteImport } from './routes/dashboard.artwork.upload'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop_/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrackProductionRoute =
  DashboardTrackProductionRouteImport.update({
    id: '/track-production',
    path: '/track-production',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReorderRoute = DashboardReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArtworkRoute = DashboardArtworkRouteImport.update({
  id: '/artwork',
  path: '/artwork',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddressesRoute = DashboardAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductionRoute = AdminProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtworkRoute = AdminArtworkRouteImport.update({
  id: '/artwork',
  path: '/artwork',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardArtworkUploadRoute = DashboardArtworkUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardArtworkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/register': typeof RegisterRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artwork': typeof AdminArtworkRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/artwork': typeof DashboardArtworkRouteWithChildren
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/track-production': typeof DashboardTrackProductionRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/artwork/upload': typeof DashboardArtworkUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/register': typeof RegisterRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artwork': typeof AdminArtworkRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/artwork': typeof DashboardArtworkRouteWithChildren
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/track-production': typeof DashboardTrackProductionRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/artwork/upload': typeof DashboardArtworkUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/register': typeof RegisterRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artwork': typeof AdminArtworkRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/artwork': typeof DashboardArtworkRouteWithChildren
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/track-production': typeof DashboardTrackProductionRoute
  '/shop_/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/artwork/upload': typeof DashboardArtworkUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faqs'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/policies'
    | '/register'
    | '/request-quote'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/testimonials'
    | '/track-order'
    | '/admin/analytics'
    | '/admin/artwork'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/production'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/dashboard/addresses'
    | '/dashboard/artwork'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/quotes'
    | '/dashboard/reorder'
    | '/dashboard/support'
    | '/dashboard/track-production'
    | '/shop/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/artwork/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/policies'
    | '/register'
    | '/request-quote'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/testimonials'
    | '/track-order'
    | '/admin/analytics'
    | '/admin/artwork'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/production'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/dashboard/addresses'
    | '/dashboard/artwork'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/quotes'
    | '/dashboard/reorder'
    | '/dashboard/support'
    | '/dashboard/track-production'
    | '/shop/$slug'
    | '/admin'
    | '/dashboard'
    | '/dashboard/artwork/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faqs'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/policies'
    | '/register'
    | '/request-quote'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/testimonials'
    | '/track-order'
    | '/admin/analytics'
    | '/admin/artwork'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/production'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/dashboard/addresses'
    | '/dashboard/artwork'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/quotes'
    | '/dashboard/reorder'
    | '/dashboard/support'
    | '/dashboard/track-production'
    | '/shop_/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/artwork/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BulkOrdersRoute: typeof BulkOrdersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRoute
  RegisterRoute: typeof RegisterRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop_/$slug': {
      id: '/shop_/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/track-production': {
      id: '/dashboard/track-production'
      path: '/track-production'
      fullPath: '/dashboard/track-production'
      preLoaderRoute: typeof DashboardTrackProductionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reorder': {
      id: '/dashboard/reorder'
      path: '/reorder'
      fullPath: '/dashboard/reorder'
      preLoaderRoute: typeof DashboardReorderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/artwork': {
      id: '/dashboard/artwork'
      path: '/artwork'
      fullPath: '/dashboard/artwork'
      preLoaderRoute: typeof DashboardArtworkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/addresses': {
      id: '/dashboard/addresses'
      path: '/addresses'
      fullPath: '/dashboard/addresses'
      preLoaderRoute: typeof DashboardAddressesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/production': {
      id: '/admin/production'
      path: '/production'
      fullPath: '/admin/production'
      preLoaderRoute: typeof AdminProductionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artwork': {
      id: '/admin/artwork'
      path: '/artwork'
      fullPath: '/admin/artwork'
      preLoaderRoute: typeof AdminArtworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/artwork/upload': {
      id: '/dashboard/artwork/upload'
      path: '/upload'
      fullPath: '/dashboard/artwork/upload'
      preLoaderRoute: typeof DashboardArtworkUploadRouteImport
      parentRoute: typeof DashboardArtworkRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArtworkRoute: typeof AdminArtworkRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductionRoute: typeof AdminProductionRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArtworkRoute: AdminArtworkRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductionRoute: AdminProductionRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardArtworkRouteChildren {
  DashboardArtworkUploadRoute: typeof DashboardArtworkUploadRoute
}

const DashboardArtworkRouteChildren: DashboardArtworkRouteChildren = {
  DashboardArtworkUploadRoute: DashboardArtworkUploadRoute,
}

const DashboardArtworkRouteWithChildren =
  DashboardArtworkRoute._addFileChildren(DashboardArtworkRouteChildren)

interface DashboardRouteChildren {
  DashboardAddressesRoute: typeof DashboardAddressesRoute
  DashboardArtworkRoute: typeof DashboardArtworkRouteWithChildren
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardReorderRoute: typeof DashboardReorderRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTrackProductionRoute: typeof DashboardTrackProductionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddressesRoute: DashboardAddressesRoute,
  DashboardArtworkRoute: DashboardArtworkRouteWithChildren,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardReorderRoute: DashboardReorderRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTrackProductionRoute: DashboardTrackProductionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BulkOrdersRoute: BulkOrdersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRoute,
  RegisterRoute: RegisterRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrackOrderRoute: TrackOrderRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
